theme: jekyll-theme-minimal
title: BlindSDR
description: Software to enable blind radio enthusiasts to enjoy software defined radio.
theme: minima

github_username: blindsdr

minima:
  show_excerpts: true
